// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Publisher            string   `protobuf:"bytes,4,opt,name=Publisher,proto3" json:"Publisher,omitempty"`
	Series               string   `protobuf:"bytes,5,opt,name=Series,proto3" json:"Series,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
	ISBN                 string   `protobuf:"bytes,7,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	PublishDate          string   `protobuf:"bytes,8,opt,name=PublishDate,proto3" json:"PublishDate,omitempty"`
	Binding              string   `protobuf:"bytes,9,opt,name=Binding,proto3" json:"Binding,omitempty"`
	Format               string   `protobuf:"bytes,10,opt,name=Format,proto3" json:"Format,omitempty"`
	Pages                int64    `protobuf:"varint,11,opt,name=Pages,proto3" json:"Pages,omitempty"`
	WordCount            int64    `protobuf:"varint,12,opt,name=WordCount,proto3" json:"WordCount,omitempty"`
	ContentIntro         string   `protobuf:"bytes,13,opt,name=ContentIntro,proto3" json:"ContentIntro,omitempty"`
	AuthorIntro          string   `protobuf:"bytes,14,opt,name=AuthorIntro,proto3" json:"AuthorIntro,omitempty"`
	Menu                 string   `protobuf:"bytes,15,opt,name=Menu,proto3" json:"Menu,omitempty"`
	Volume               int64    `protobuf:"varint,16,opt,name=Volume,proto3" json:"Volume,omitempty"`
	UniqueCode           string   `protobuf:"bytes,17,opt,name=UniqueCode,proto3" json:"UniqueCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInfo) Reset()         { *m = BookInfo{} }
func (m *BookInfo) String() string { return proto.CompactTextString(m) }
func (*BookInfo) ProtoMessage()    {}
func (*BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4af5ead98078a7d7, []int{0}
}
func (m *BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInfo.Unmarshal(m, b)
}
func (m *BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInfo.Marshal(b, m, deterministic)
}
func (dst *BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInfo.Merge(dst, src)
}
func (m *BookInfo) XXX_Size() int {
	return xxx_messageInfo_BookInfo.Size(m)
}
func (m *BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BookInfo proto.InternalMessageInfo

func (m *BookInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookInfo) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *BookInfo) GetSeries() string {
	if m != nil {
		return m.Series
	}
	return ""
}

func (m *BookInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BookInfo) GetISBN() string {
	if m != nil {
		return m.ISBN
	}
	return ""
}

func (m *BookInfo) GetPublishDate() string {
	if m != nil {
		return m.PublishDate
	}
	return ""
}

func (m *BookInfo) GetBinding() string {
	if m != nil {
		return m.Binding
	}
	return ""
}

func (m *BookInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *BookInfo) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *BookInfo) GetWordCount() int64 {
	if m != nil {
		return m.WordCount
	}
	return 0
}

func (m *BookInfo) GetContentIntro() string {
	if m != nil {
		return m.ContentIntro
	}
	return ""
}

func (m *BookInfo) GetAuthorIntro() string {
	if m != nil {
		return m.AuthorIntro
	}
	return ""
}

func (m *BookInfo) GetMenu() string {
	if m != nil {
		return m.Menu
	}
	return ""
}

func (m *BookInfo) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *BookInfo) GetUniqueCode() string {
	if m != nil {
		return m.UniqueCode
	}
	return ""
}

type GetRequest struct {
	ISBN                 string   `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4af5ead98078a7d7, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetISBN() string {
	if m != nil {
		return m.ISBN
	}
	return ""
}

type PutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4af5ead98078a7d7, []int{2}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BookInfo)(nil), "api.BookInfo")
	proto.RegisterType((*GetRequest)(nil), "api.GetRequest")
	proto.RegisterType((*PutResponse)(nil), "api.PutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BookInfo, error)
	Put(ctx context.Context, in *BookInfo, opts ...grpc.CallOption) (*PutResponse, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BookInfo, error) {
	out := new(BookInfo)
	err := c.cc.Invoke(ctx, "/api.Book/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) Put(ctx context.Context, in *BookInfo, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/api.Book/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServer is the server API for Book service.
type BookServer interface {
	Get(context.Context, *GetRequest) (*BookInfo, error)
	Put(context.Context, *BookInfo) (*PutResponse, error)
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Book/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Book/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).Put(ctx, req.(*BookInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Book_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Book_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_4af5ead98078a7d7) }

var fileDescriptor_api_4af5ead98078a7d7 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcd, 0x8e, 0xda, 0x30,
	0x10, 0xc7, 0x49, 0xc3, 0x57, 0x06, 0x28, 0xd4, 0xaa, 0xaa, 0x11, 0xaa, 0xaa, 0x28, 0x97, 0xe6,
	0xc4, 0xa1, 0x7d, 0x82, 0x42, 0x55, 0xc4, 0xa1, 0x2b, 0x14, 0xd8, 0x5d, 0xed, 0x31, 0x2c, 0xb3,
	0x60, 0x2d, 0xd8, 0xc1, 0xb1, 0x5f, 0x71, 0x9f, 0x6b, 0x65, 0x3b, 0x6c, 0xc2, 0xcd, 0xff, 0xdf,
	0x7c, 0x8f, 0x07, 0xa2, 0xbc, 0xe0, 0xb3, 0x42, 0x49, 0x2d, 0x59, 0x98, 0x17, 0x3c, 0x79, 0x0b,
	0xa1, 0x3f, 0x97, 0xf2, 0x75, 0x25, 0x5e, 0x24, 0xfb, 0x0a, 0x9d, 0x2d, 0xd7, 0x27, 0xc2, 0x20,
	0x0e, 0xd2, 0x28, 0xf3, 0xc2, 0xd2, 0xb5, 0xe2, 0xcf, 0x84, 0x9f, 0xe2, 0x20, 0x0d, 0x33, 0x2f,
	0xd8, 0x37, 0xe8, 0xfe, 0x31, 0xfa, 0x28, 0x15, 0x86, 0xce, 0xb9, 0x52, 0xec, 0x3b, 0x44, 0x6b,
	0xb3, 0x3b, 0xf1, 0xf2, 0x48, 0x0a, 0xdb, 0xce, 0x54, 0x03, 0x1b, 0xb5, 0x21, 0xc5, 0xa9, 0xc4,
	0x8e, 0x8f, 0xf2, 0x8a, 0x31, 0x68, 0x6f, 0xf3, 0x43, 0x89, 0xdd, 0x38, 0x4c, 0xa3, 0xcc, 0xbd,
	0x2d, 0x5b, 0x6d, 0xe6, 0x77, 0xd8, 0x73, 0x9e, 0xee, 0xcd, 0x62, 0x18, 0x54, 0xc9, 0xfe, 0xe6,
	0x9a, 0xb0, 0xef, 0x4c, 0x4d, 0xc4, 0x10, 0x7a, 0x73, 0x2e, 0xf6, 0x5c, 0x1c, 0x30, 0x72, 0xd6,
	0xab, 0xb4, 0xb5, 0xff, 0x49, 0x75, 0xce, 0x35, 0x82, 0xaf, 0xed, 0x95, 0x9b, 0x2f, 0x3f, 0x50,
	0x89, 0x83, 0x6a, 0x3e, 0x2b, 0xec, 0x1c, 0x8f, 0x52, 0xed, 0x17, 0xd2, 0x08, 0x8d, 0x43, 0x67,
	0xa9, 0x01, 0x4b, 0x60, 0xb8, 0x90, 0x42, 0x93, 0xd0, 0x2b, 0xa1, 0x95, 0xc4, 0x91, 0xcb, 0x78,
	0xc3, 0x6c, 0xaf, 0x7e, 0x27, 0xde, 0xe5, 0xb3, 0xef, 0xb5, 0x81, 0xec, 0x84, 0xff, 0x49, 0x18,
	0x1c, 0xfb, 0x09, 0xed, 0xdb, 0x76, 0xf9, 0x20, 0x4f, 0xe6, 0x4c, 0x38, 0x71, 0x45, 0x2b, 0xc5,
	0x7e, 0x00, 0xdc, 0x0b, 0x7e, 0x31, 0xb4, 0x90, 0x7b, 0xc2, 0x2f, 0x2e, 0xa2, 0x41, 0x92, 0x18,
	0x60, 0x49, 0x3a, 0xa3, 0x8b, 0xa1, 0x52, 0x7f, 0xec, 0x2e, 0xa8, 0x77, 0x97, 0x8c, 0xec, 0xee,
	0x74, 0x46, 0x65, 0x21, 0x45, 0x49, 0xbf, 0x9e, 0xa0, 0x6d, 0x3f, 0x9e, 0xfd, 0x84, 0x70, 0x49,
	0x9a, 0x8d, 0x67, 0xf6, 0x32, 0xea, 0x14, 0xd3, 0x91, 0x03, 0xd7, 0xdb, 0x48, 0x5a, 0x2c, 0x85,
	0x70, 0x6d, 0x34, 0xbb, 0xe5, 0xd3, 0x89, 0x93, 0x8d, 0xc4, 0x49, 0x6b, 0xd7, 0x75, 0x07, 0xf6,
	0xfb, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x8d, 0xf7, 0x1e, 0x6d, 0x02, 0x00, 0x00,
}
